apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  template:
    spec:
      containers:
        - name: graphql
          image: us-central1-docker.pkg.dev/project-aims-dev/docker-registry-aims-dev/aims-graphql