apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: graphql
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graphql
  minReplicas: 1
  maxReplicas: 1