apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app.kubernetes.io/name: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: graphql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: graphql
    spec:
      containers:
        - name: graphql
          image: aims-graphql
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: graphql-cnfgmp
            - secretRef:
                name: graphql
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /?query=%7B__typename%7D
              port: http
              httpHeaders:
              - name: apollo-require-preflight
                value: "true"
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /?query=%7B__typename%7D
              port: http
              httpHeaders:
              - name: apollo-require-preflight
                value: "true"
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 125Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 125Mi
              memory: 512Mi