apiVersion: apps/v1
kind: Deployment
metadata:
  name: well-mgmt-svc-v2
  labels:
    app.kubernetes.io/name: well-mgmt-svc-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: well-mgmt-svc-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: well-mgmt-svc-v2
    spec:
      serviceAccountName: aims-qa-well-mgmt-sa
