resources:
  - ../base
  - serviceaccount.yaml

namespace: aims-qa
secretGenerator:
  - name: well-mgmt-svc-v2
    behavior: merge
    envs:
    - qa-secrets.env
    
patches:
  - hpa.yaml
  - deployment.yaml