apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: aims-qa-wi-user-sa@project-aims-qa.iam.gserviceaccount.com
  name: aims-qa-well-mgmt-sa
  namespace: aims-qa