apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: ui
spec:
  template:
    spec:
      containers:
        - name: ui
          image: us-central1-docker.pkg.dev/project-aims-dev/docker-registry-aims-dev/aims-ui