steps:
  - id: Install the dependencies
    name: node
    entrypoint: yarn
    args: ['install']
  
  - id: Update secrets values
    name: bash
    secretEnv: ['DEV_DB_PASS', 'DEV_DB_USER', 'QA_DB_PASS', 'QA_DB_USER', 'PROD_DB_PASS', 'PROD_DB_USER']
    entrypoint: bash
    args:
    - -c
    - |
      cat << EOF > k8s/dev/dev-secrets.env
      DATABASE_HOST=10.14.1.3
      DATABASE_USERNAME=$$DEV_DB_USER
      DATABASE_PASSWORD=$$DEV_DB_PASS
      EOF
      
      cat << EOF > k8s/qa/qa-secrets.env
      DATABASE_HOST=10.38.80.5
      DATABASE_USERNAME=$$QA_DB_USER
      DATABASE_PASSWORD=$$QA_DB_PASS
      EOF

      cat << EOF > k8s/prod/prod-secrets.env
      DATABASE_HOST=10.28.33.2
      DATABASE_USERNAME=$$PROD_DB_USER
      DATABASE_PASSWORD=$$PROD_DB_PASS
      EOF

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
    - -c
    - |
      export DOCKER_BUILDKIT=1
      docker pull $_IMAGE_NAME:latest
      docker build -t $_IMAGE_NAME:$COMMIT_SHA \
              -t $_IMAGE_NAME:latest \
              --cache-from $_IMAGE_NAME:latest \
              .
      docker push --all-tags $_IMAGE_NAME
  
  - id: Deploy to gke cluster 
    name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
    - -xe
    - -c
    - |
      gcloud beta deploy releases create user-mgmt-svc-release-${SHORT_SHA} \
                          --delivery-pipeline aims-user-mgmt-svc \
                          --region ${_REGION} \
                          --description "$(git log -1  --pretty='%s')" \
                          --images=aims-user-mgmt-svc=$_IMAGE_NAME:$COMMIT_SHA \
                          --annotations "commit_ui=$COMMIT_SHA"

timeout: 1000s
options:
  logging: GCS_ONLY
logsBucket: gs://aims_cloud_build_logs
substitutions:
  _IMAGE_NAME: us-central1-docker.pkg.dev/project-aims-dev/docker-registry-aims-dev/aims-user-mgmt-svc
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/dev_db_user/versions/1
    env: 'DEV_DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/dev_db_pass/versions/1
    env: 'DEV_DB_PASS'
  - versionName: projects/$PROJECT_ID/secrets/qa_db_user/versions/1
    env: 'QA_DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/qa_db_pass/versions/1
    env: 'QA_DB_PASS'
  - versionName: projects/$PROJECT_ID/secrets/prod_db_user/versions/1
    env: 'PROD_DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/prod_db_pass/versions/1
    env: 'PROD_DB_PASS'