apiVersion: v1
kind: Service
metadata:
  name: user-mgmt-svc
  labels:
    app.kubernetes.io/name: user-mgmt-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app.kubernetes.io/name: user-mgmt-svc