apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-mgmt-svc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-mgmt-svc
  minReplicas: 1
  maxReplicas: 5