import { IsUUID } from "class-validator";
import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { CreateColonyRequestDTO } from "./colony-request.dto";
import { ClusterOrColonyType } from "../enums/cluster-or-colony-type";

export class ColonyMetadata {

    @ApiProperty({ description: "Clonality of the clusters" })
	clonality: string;

    @ApiProperty({ description: "Sum area of all the clusters" })
	area: number;

    @ApiProperty({ description: "Average circularity of the clusters" })
	circularity: number;

    @ApiProperty({ description: "Total number of cells in a given colony. Or sum of all the cells in individual clusters" })
	cells: number;

    @ApiProperty({ description: "Total number of clusters for the given colony" })
	numberOfClusters: number;
}

export class ColonyDTO extends CreateColonyRequestDTO{
    @ApiProperty()
    @IsUUID('all')
    id:string;

    @IsUUID("all")
    @ApiProperty({ description: "imageAnalysisRequest id of Colony",required:false})
    imageAnalysisRequestId: string;

    //commenting this code as we were not using metadata
    // @ApiPropertyOptional({ description: "Autogenerated metadata which gives summary on the colony and its associated clusters" })
    // metadata: ColonyMetadata;

    @ApiProperty({enum:['MANUAL','SYSTEMGENERATED','EDITED'],required:false,description: "type of the colony"})
    type:typeof ClusterOrColonyType;

    @ApiProperty({required:false,description: "checks if the colony is active or soft deleted"})
    isActive:boolean;
}