steps:
  - id: Update secrets values
    name: bash
    secretEnv: ['DEV_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID', 'DEV_GOOGLE_ZARR_AUTH_PRIVATE_KEY', 'DEV_GOOGLE_ZARR_AUTH_CLIENT_EMAIL',
     'DEV_GOOGLE_ZARR_AUTH_CLIENT_ID', 'DEV_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL',
     'QA_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID', 'QA_GOOGLE_ZARR_AUTH_PRIVATE_KEY', 'QA_GOOGLE_ZARR_AUTH_CLIENT_EMAIL',
     'QA_GOOGLE_ZARR_AUTH_CLIENT_ID', 'QA_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL',
     'PROD_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID', 'PROD_GOOGLE_ZARR_AUTH_PRIVATE_KEY', 'PROD_GOOGLE_ZARR_AUTH_CLIENT_EMAIL',
     'PROD_GOOGLE_ZARR_AUTH_CLIENT_ID', 'PROD_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL']
    entrypoint: bash
    args:
    - -c
    - |
      cat << EOF > k8s/dev/dev-secrets.env
      GOOGLE_ZARR_AUTH_PROJECT_ID=$_DEV_GOOGLE_ZARR_AUTH_PROJECT_ID
      GOOGLE_ZARR_AUTH_PRIVATET_KEY_ID=$$DEV_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID
      GOOGLE_ZARR_AUTH_PRIVATET_KEY=$$DEV_GOOGLE_ZARR_AUTH_PRIVATE_KEY
      GOOGLE_ZARR_AUTH_CLIENT_EMAIL=$$DEV_GOOGLE_ZARR_AUTH_CLIENT_EMAIL
      GOOGLE_ZARR_AUTH_CLIENT_ID=$$DEV_GOOGLE_ZARR_AUTH_CLIENT_ID
      GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL=$$DEV_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL
      GOOGLE_CLOUD_BUCKET=$_DEV_GOOGLE_CLOUD_BUCKET
      STORAGE_URL_ORIGIN=$_STORAGE_URL_ORIGIN
      CDN_URL=$_DEV_CDN_URL
      EOF
      
      cat << EOF > k8s/qa/qa-secrets.env
      GOOGLE_ZARR_AUTH_PROJECT_ID=$_QA_GOOGLE_ZARR_AUTH_PROJECT_ID
      GOOGLE_ZARR_AUTH_PRIVATET_KEY_ID=$$QA_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID
      GOOGLE_ZARR_AUTH_PRIVATET_KEY=$$QA_GOOGLE_ZARR_AUTH_PRIVATE_KEY
      GOOGLE_ZARR_AUTH_CLIENT_EMAIL=$$QA_GOOGLE_ZARR_AUTH_CLIENT_EMAIL
      GOOGLE_ZARR_AUTH_CLIENT_ID=$$QA_GOOGLE_ZARR_AUTH_CLIENT_ID
      GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL=$$QA_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL
      GOOGLE_CLOUD_BUCKET=$_QA_GOOGLE_CLOUD_BUCKET
      STORAGE_URL_ORIGIN=$_STORAGE_URL_ORIGIN
      CDN_URL=$_QA_CDN_URL
      EOF

      cat << EOF > k8s/prod/prod-secrets.env
      GOOGLE_ZARR_AUTH_PROJECT_ID=$_PROD_GOOGLE_ZARR_AUTH_PROJECT_ID
      GOOGLE_ZARR_AUTH_PRIVATET_KEY_ID=$$PROD_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID
      GOOGLE_ZARR_AUTH_PRIVATET_KEY=$$PROD_GOOGLE_ZARR_AUTH_PRIVATE_KEY
      GOOGLE_ZARR_AUTH_CLIENT_EMAIL=$$PROD_GOOGLE_ZARR_AUTH_CLIENT_EMAIL
      GOOGLE_ZARR_AUTH_CLIENT_ID=$$PROD_GOOGLE_ZARR_AUTH_CLIENT_ID
      GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL=$$PROD_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL
      GOOGLE_CLOUD_BUCKET=$_PROD_GOOGLE_CLOUD_BUCKET
      STORAGE_URL_ORIGIN=$_STORAGE_URL_ORIGIN
      CDN_URL=$_PROD_CDN_URL
      EOF

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
    - -c
    - |
      export DOCKER_BUILDKIT=1
      docker pull $_IMAGE_NAME:latest
      docker build -t $_IMAGE_NAME:$COMMIT_SHA \
              -t $_IMAGE_NAME:latest \
              --cache-from $_IMAGE_NAME:latest \
              .
      docker push --all-tags $_IMAGE_NAME
  
  - id: Deploy to gke cluster 
    name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
    - -xe
    - -c
    - |
      gcloud beta deploy releases create graphql-release-${SHORT_SHA} \
                          --delivery-pipeline aims-graphql \
                          --region ${_REGION} \
                          --description "$(git log -1  --pretty='%s')" \
                          --images=aims-graphql=$_IMAGE_NAME:$COMMIT_SHA \
                          --annotations "commit_ui=$COMMIT_SHA"

timeout: 3600s 
options:
  logging: GCS_ONLY
logsBucket: gs://aims_cloud_build_logs
substitutions:
  _IMAGE_NAME: us-central1-docker.pkg.dev/project-aims-dev/docker-registry-aims-dev/aims-graphql
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/dev_google_zarr_auth_private_key_id/versions/1
    env: 'DEV_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID'
  - versionName: projects/$PROJECT_ID/secrets/dev_google_zarr_auth_private_key/versions/1
    env: 'DEV_GOOGLE_ZARR_AUTH_PRIVATE_KEY'
  - versionName: projects/$PROJECT_ID/secrets/dev_google_zarr_auth_client_id/versions/1
    env: 'DEV_GOOGLE_ZARR_AUTH_CLIENT_ID'
  - versionName: projects/$PROJECT_ID/secrets/dev_google_zarr_auth_client_email/versions/1
    env: 'DEV_GOOGLE_ZARR_AUTH_CLIENT_EMAIL'
  - versionName: projects/$PROJECT_ID/secrets/dev_google_zarr_auth_client_cert_url/versions/1
    env: 'DEV_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL'
  - versionName: projects/$PROJECT_ID/secrets/qa_google_zarr_auth_private_key_id/versions/1
    env: 'QA_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID'
  - versionName: projects/$PROJECT_ID/secrets/qa_google_zarr_auth_private_key/versions/1
    env: 'QA_GOOGLE_ZARR_AUTH_PRIVATE_KEY'
  - versionName: projects/$PROJECT_ID/secrets/qa_google_zarr_auth_client_id/versions/1
    env: 'QA_GOOGLE_ZARR_AUTH_CLIENT_ID'
  - versionName: projects/$PROJECT_ID/secrets/qa_google_zarr_auth_client_email/versions/1
    env: 'QA_GOOGLE_ZARR_AUTH_CLIENT_EMAIL'
  - versionName: projects/$PROJECT_ID/secrets/qa_google_zarr_auth_client_cert_url/versions/1
    env: 'QA_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL'
  - versionName: projects/$PROJECT_ID/secrets/prod_google_zarr_auth_private_key_id/versions/1
    env: 'PROD_GOOGLE_ZARR_AUTH_PRIVATE_KEY_ID'
  - versionName: projects/$PROJECT_ID/secrets/prod_google_zarr_auth_private_key/versions/1
    env: 'PROD_GOOGLE_ZARR_AUTH_PRIVATE_KEY'
  - versionName: projects/$PROJECT_ID/secrets/prod_google_zarr_auth_client_id/versions/1
    env: 'PROD_GOOGLE_ZARR_AUTH_CLIENT_ID'
  - versionName: projects/$PROJECT_ID/secrets/prod_google_zarr_auth_client_email/versions/1
    env: 'PROD_GOOGLE_ZARR_AUTH_CLIENT_EMAIL'
  - versionName: projects/$PROJECT_ID/secrets/prod_google_zarr_auth_client_cert_url/versions/1
    env: 'PROD_GOOGLE_ZARR_AUTH_CLIENT_X509_CERT_URL'