apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-mgmt-svc
  labels:
    app.kubernetes.io/name: run-mgmt-svc
spec:
  template:
    spec:
      containers:
        - name: aims-run-mgmt-svc
          image: us-central1-docker.pkg.dev/project-aims-dev/docker-registry-aims-dev/aims-run-mgmt-svc