apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: run-mgmt-svc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: run-mgmt-svc
  minReplicas: 1
  maxReplicas: 1