apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "aims-iap-backend"}'
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app.kubernetes.io/name: gateway