apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: well-mgmt-svc-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: well-mgmt-svc-v2
  minReplicas: 1
  maxReplicas: 1