apiVersion: apps/v1
kind: Deployment
metadata:
  name: well-mgmt-svc-v2
  labels:
    app.kubernetes.io/name: well-mgmt-svc-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: well-mgmt-svc-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: well-mgmt-svc-v2
    spec:
      initContainers:
        - name: well-mgmt-svc-v2-migration
          image: aims-well-mgmt-svc-v2
          command: [ 'npx', 'typeorm', 'migration:run', '-d', 'typeorm-cli.config' ]
          envFrom:
            - secretRef:
                name: well-mgmt-svc-v2
      containers:
        - name: well-mgmt-svc-v2
          image: aims-well-mgmt-svc-v2
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: well-mgmt-svc-v2
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 125Mi
              memory: 1000Mi
            requests:
              cpu: 500m
              ephemeral-storage: 125Mi
              memory: 512Mi
