apiVersion: v1
kind: Service
metadata:
  name: well-mgmt-svc-v2
  labels:
    app.kubernetes.io/name: well-mgmt-svc-v2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: well-mgmt-svc-v2