-- Run after roles table is created and data is seeded into the roles table.
do $$ 


    declare SYSTEM_ID uuid := (SELECT id FROM public."user" where "user".email = 'system@cellinobio.com');

    declare ADMIN_ROLE uuid := (SELECT id from public."role" where "role".name = 'Admin');
    declare RUN_MANAGER_ROLE uuid := (SELECT id from public."role" where "role".name = 'Run Manager');
    declare PLATE_REVIEWER_ROLE uuid := (SELECT id from public."role" where "role".name = 'Plate Reviewer');
    declare RUN_REVIEWER_ROLE uuid := (SELECT id from public."role" where "role".name = 'Run Reviewer');
    declare DATA_VIEWER_ROLE uuid := (SELECT id from public."role" where "role".name = 'Data Viewer');

    begin
        insert into
            "user" (
                "first_name",
                "last_name",
                "email",
                "is_active",
                "created_at",
                "created_by",
                "modified_at",
                "modified_by",
                "role_id"
            )
        values
            (
                'Sharanappa',
                'Dubale',
                'sdubale@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Aarya Devarla',
                'Boya',
                'aboya@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Abhijit',
                'Kulkarni',
                'akulkarni@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Accounts',
                'Payable',
                'ap@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Alex',
                'Hersh',
                'ahersh@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Alex',
                'Stange',
                'astange@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Andrew',
                'Donheiser',
                'adonheiser@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Anil',
                'Sanugondla',
                'asanugondla@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Anna',
                'Worford',
                'aworford@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Anne',
                'Bennett',
                'abennett@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                PLATE_REVIEWER_ROLE
            ),
            (
                'Anthia',
                'Toure',
                'atoure@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Arnaldo',
                'Pereira',
                'apereira@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Arpit',
                'Maheshwari',
                'amaheshwari@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Bar',
                'Makovoz',
                'bmakovoz@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Barbara',
                'Nelsen',
                'bnelsen@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Brooke',
                'Barrettsmith',
                'bbarrettsmith@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Catherine',
                'Pilsmaker',
                'cpilsmaker@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                RUN_REVIEWER_ROLE
            ),
            (
                'Christopher',
                'Harrison',
                'charrison@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Deniz',
                'Aksel',
                'daksel@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Diwakar',
                'Cherukumilli',
                'dcherukumilli@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Emre',
                'Toner',
                'etoner@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Erik',
                'Snow',
                'esnow@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Ethan',
                'Goldman',
                'egoldman@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Gaurav',
                'Gharat',
                'ggharat@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'George',
                'Harb',
                'gharb@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Hari Chandhana',
                'Bandaru',
                'hbandaru@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Jade',
                'Jen',
                'jjen@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Jason',
                'Natale',
                'jnatale@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Julia',
                'Hutchinson',
                'jhutchinson@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Julie',
                'Andriolo',
                'jandriolo@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Kayla',
                'Sohl',
                'ksohl@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Kean',
                'Villarta',
                'kvillarta@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Kien',
                'Tran',
                'ktran@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Kimberly',
                'Ha',
                'kha@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Lorianne',
                'Kwak',
                'lkwak@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Lukas',
                'Vasadi',
                'lvasadi@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Lydia',
                'Skrabonja',
                'lskrabonja@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Maria',
                'Silva',
                'msilva@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                ADMIN_ROLE
            ),
            (
                'Mariangela',
                'Amenduni',
                'mamenduni@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Marinna',
                'Madrid',
                'mmadrid@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                ADMIN_ROLE
            ),
            (
                'Matthew',
                'Sullivan',
                'msullivan@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Matthias',
                'Wagner',
                'mwagner@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Maya',
                'Berlin-Udi',
                'mberlinudi@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Mohtasim',
                'Narmawala',
                'mnarmawala@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Nabiha',
                'Saklayen',
                'nsaklayen@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Nalee',
                'Yang',
                'nyang@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Ozge',
                'Whiting',
                'owhiting@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Paulette',
                'Dillon',
                'pdillon@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Prasanjit',
                'Achary',
                'pachary@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Pushpa Sri',
                'Dodda',
                'pdodda@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Ralitsa',
                'Mintcheva',
                'rmintcheva@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Ronald',
                'Balcius',
                'rbalcius@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Samad',
                'Khan',
                'skhan@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Sangkyun',
                'Lee',
                'slee@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Scott',
                'Luro',
                'sluro@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Sravani',
                'Kusuma',
                'skusuma@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Stefanie',
                'Morgan',
                'smorgan@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                RUN_MANAGER_ROLE
            ),
            (
                'Steven',
                'Nagle',
                'snagle@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Taufiq',
                'Dhanani',
                'tdhanani@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Varun',
                'Dixit',
                'vdixit@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Vijay',
                'Chandrasekaran',
                'vchandrasekaran@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Vijay',
                'Nandigam',
                'vnandigam@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Vittorio',
                'Sebastiano',
                'vsebastiano@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Willie',
                'Reaves',
                'wreaves@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            ),
            (
                'Yutian',
                'Ling',
                'yling@cellinobio.com',
                TRUE,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                CURRENT_TIMESTAMP,
                SYSTEM_ID,
                DATA_VIEWER_ROLE
            );

end $$