apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  
secretGenerator:
  - name: run-mgmt-svc
    envs:
    - secrets.env
generatorOptions:
  disableNameSuffixHash: true