apiVersion: v1
kind: Service
metadata:
  name: run-mgmt-svc
  labels:
    app.kubernetes.io/name: run-mgmt-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: run-mgmt-svc