version: '3.8'
services:
  postgre_db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: cellino
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - backend


  aims_run_management:
    container_name: aims_run_management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgre_db
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  db:
    driver: local