apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
    spec:
      containers:
        - name: ui
          image: aims-ui
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: ui
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 125Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 125Mi
              memory: 512Mi
